### ISSUE TITLE
Supra 98 turbo 

### ISSUE THREAD

**Issue by chiBomb** [Crypto-Wrld/server-issues#10]
Gets stuck in place if not using drift mode ... does not brake at all ... its a hardtop and suddenly a convertible !

**Comment by Boom1053** [comment]
So do to the amount of cars having this issue when activating drift mode. I have went ahead an removed drift mode completely! This in my opinion will improve FPS as several clients aren't running the drift event. Whats left to be done @Onehandedbanditt is improvement on his car handling file. Ive tested it myself and it drives like shit xD

**Comment by Boom1053** [comment]
Taken care of.
