### ISSUE TITLE
At Alta St. Apartments, the return vehicle chevron is occasionally blocked by spawning local cars.

### ISSUE THREAD

**Issue by VerveXP** [Crypto-Wrld/server-issues#11]
The red arrow, as you more than likely know lmao, is the spot that we return our cars. Not sure if you can do anything about it but it's kinda annoying having to ram them out of the way when they spawn.
![Blocked Garage](https://user-images.githubusercontent.com/97819377/152086952-2000a00f-6110-4c29-8c00-e46982d15d3c.png)

**Comment by Boom1053** [comment]
Ill be updating alta st with the new garage system shortly

**Comment by Boom1053** [comment]
Alta street has been updated with the new garage system. Problem should not continue.
