### ISSUE TITLE
Police lights

### ISSUE THREAD

**Issue by Bcole32** [Crypto-Wrld/server-issues#14]
all police lights are not working in the cars. and the doors to down stairs are not able to open up

**Comment by Boom1053** [comment]
i cant seem to recreate this light issue as im in a cop car rn using the lights. As for the doors a simple reset of the script should fix it

**Comment by Bcole32** [comment]
my bad its bc i change a button which i guess was cop lights too

**Comment by Boom1053** [comment]
all good brother man
