### ISSUE TITLE
White Widow Blunts are not working

### ISSUE THREAD

**Issue by Helios2113** [Crypto-Wrld/server-issues#15]
So picking the 8th of whatever strain and rolling works but actually smoking it does not give you any effects nor takes away stress. I have tried every blunt and none of them work.

**Comment by Boom1053** [comment]
ill see what i can get done. For the moment still have people support your store <3

**Comment by Boom1053** [comment]
i have an update for your script i just need to push it !

**Comment by Boom1053** [comment]
I have pushed this update please let me know if everything is working
