### ISSUE TITLE
The new dealership script is cool, but it breaks every 5 minutes.

### ISSUE THREAD

**Issue by VerveXP** [Crypto-Wrld/server-issues#17]
I personally can't deliver more than like 3 vehicles before it breaks on me @ PDM, Maple has been able to put some numbers up but it breaks for him usually by the end of the day. And when it breaks for PDM, if definitely breaks for Import as well. We need to get PDM done because I hear a lot of people complaining about money in the server and I feel like a lot of those complaints will settle down after they see the prices being presented at PDM, but since I can't get one of everything and start selling cars, people who're at entry levels of money have no choice but to shoot for cars that multi-millionaires can buy.

**Comment by Boom1053** [comment]
I need you guys to let me know when this happen till the next script update as of now i would manually remove ya from the order.
