### ISSUE TITLE
Sports Category Missing

### ISSUE THREAD

**Issue by VerveXP** [Crypto-Wrld/server-issues#2]
The "Sports" category is missing from the Vanilla Car Shop in Premium Deluxe Motorsport.

**Comment by VerveXP** [comment]
![Sports Missing](https://user-images.githubusercontent.com/97819377/149647492-00460930-ad5b-452d-97a7-4e3cdf62ef26.png)

**Comment by Boom1053** [comment]
Thank you for bringing this to my attention! I have went ahead and added the respected category group
