### ISSUE TITLE
So the update to the menu removed the menu entirely for me. The blue chevrons aren't there anymore, discovered this yesterday, forgor the ticket.

### ISSUE THREAD

**Issue by VerveXP** [Crypto-Wrld/server-issues#20]
![Screenshot 2022-02-27 184115](https://user-images.githubusercontent.com/97819377/155904964-73146dda-b398-4962-850d-4e84b6eadd1d.png)

**Comment by Boom1053** [comment]
This new update aint what it seems >:O but for now it should be working

**Comment by Boom1053** [comment]
Still waiting for these guys to fix it. for now please contact an admin when your online to restart the okokvehicleshop script while your in game so it clicks.
