### ISSUE TITLE
sheriff ford taurus

### ISSUE THREAD

**Issue by Bcole32** [Crypto-Wrld/server-issues#22]
the sheriff ford taurus name is put in wrong. if u spwan it pulls out the pd ford taurus and the sheriff ford taurus

**Comment by Boom1053** [comment]
Is this still an issue?

**Comment by Bcole32** [comment]
Yes

**Comment by Bcole32** [comment]
I would of fixed my self. But i dont have that access to do so

**Comment by Boom1053** [comment]
New cars are coming into play so the list will get redone!
