### ISSUE TITLE
Recycling Center Script Issues

### ISSUE THREAD

**Issue by itsallybear** [Crypto-Wrld/server-issues#28]
there is an issue with the recycling center at postal 9241. I know this doesn't happen frequently, but it seems prior to closing (not sure how many mins prior to closing) if you enter the recycling center (as it offers you to do), it teleports you down to the docks, right next to postal 10124. 

The other issue with that is, if you get downed on your way to the recycling center (9241), whenever you get to the hospital and check in, it sends you back to the recycling center, where you'll still be bleeding out. Today, when this happened, I asked the Gods to revive me. When I was revived, it worked, but I was stuck inside the wall above the door. The only fix I could get was to fly out, and fly back in. 

Just wanted to be sure to report it, so it's on the record.

**Comment by the-travisty** [comment]
Something similar is also happening at the Paleto Bay recycling center. When people enter they end up falling through the world indefinitely and never reaching the interior

**Comment by Boom1053** [comment]
I believe i have fixed this in 3.0 if anyone is able to test it please let me know with opening a new ticket!
