### ISSUE TITLE
Jewelry Store Prices got reset.

### ISSUE THREAD

**Issue by VerveXP** [Crypto-Wrld/server-issues#4]
It seems like the Jewelry store prices for Rings and Necklaces got reset. Just bringing this to your attention because if I didn't someone else will and I like providing you with screenshots Papa Boom
![Rings](https://user-images.githubusercontent.com/97819377/151252463-45b058ce-bd9c-4fdb-aa41-5afe2f0a6141.png)
![Necklaces](https://user-images.githubusercontent.com/97819377/151252467-c7aa433b-c10d-4bac-871b-b6a3db6ab40a.png)
.

**Comment by Boom1053** [comment]
I appreciate it. Ill have a look at it and reply to this when its fixed!

**Comment by Boom1053** [comment]
@VerveXP This has been fixed!
