### ISSUE TITLE
Cop cars pulling to the left

### ISSUE THREAD

**Issue by Shadowgil316** [Crypto-Wrld/server-issues#40]
All cop cars are pulling to the left when you accelerate and stop

**Comment by Shadowgil316** [comment]
After some testing the situation is worse than i thought and we can not use them in chases do to the pulling issue. It makes it almost impossible to use in a chase

**Comment by the-travisty** [comment]
New core_vehicles script causing issues with handling. Removed for now for further testing. Should be fixed

**Comment by Boom1053** [comment]
This should not be an issue anymore.
