### ISSUE TITLE
Vehicle repair

### ISSUE THREAD

**Issue by DeeJayEhh** [Crypto-Wrld/server-issues#41]
My beloved 2020 Mercedes-Benz C63 GT AMG is now broken and can't be repaired. I've tried Benny's and an advanced repair kit. Putting in my garage and even after tsunami doesn't fix it. Even if I'd earned enough to buy another one nothing is available for sale at either dealership. Peace.

**Comment by the-travisty** [comment]
New core_vehicles script causing issues with certain cars not allowing oil changes. Removed for now for further testing. Should be fixed

**Comment by Boom1053** [comment]
Core vehicles have been removed. So this issue no longer exist.
