### ISSUE TITLE
Bean Machine Trigger is Inside The Building

### ISSUE THREAD

**Issue by VerveXP** [Crypto-Wrld/server-issues#5]
I don't think this is a priority, but I tried going to the Bean Machine and the trigger for the shop is inside the building. I'm guessing it was made with a custom interior in mind that we don't have, but just thought I'd let you know in case you wanted to move the trigger
![Bean Machine](https://user-images.githubusercontent.com/97819377/151279081-d9525440-9916-443b-bb55-16cd3aac5b3e.png)
.

**Comment by Boom1053** [comment]
This has since been fixed thank you!
