### ISSUE TITLE
Storage Unit Bug

### ISSUE THREAD

**Issue by nitrofreedom** [Crypto-Wrld/server-issues#6]
Cannot access storage units, allows me to type in pin but nothing happens after I enter it.

**Comment by Boom1053** [comment]
working on this ill update once its fix!

**Comment by Boom1053** [comment]
So the fix requires a full server update. 
Which im currently working on my desktop. 
Please be patient as this will improve more optimizations for our community for more enjoyable roleplay.

**Comment by Boom1053** [comment]
Fixed with a HUGE UPDATE on storages read about it here. https://github.com/Crypto-Wrld/change-log/commit/96c147f876da5190d7057b68229ac8334ae0b91c
